# Generated by Django 5.2 on 2025-05-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datahora',
            new_name='data_hora',
        ),
    ]
