# Generated by Django 5.2 on 2025-05-03 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_delete_usuario_rename_datahora_post_data_hora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='curtidas',
        ),
        migrations.AddField(
            model_name='post',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='posts_curtidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
