# Generated by Django 5.2 on 2025-05-04 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_curtidas_post_curtidas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='curtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
